export const TEMP_CONTACT_DATA = [
	{
		id: '1',
		name: 'Ayla Meland',
		prefix: null,
		phone: '21763438',
		picture: 'https://randomuser.me/api/portraits/med/women/41.jpg',
	},
	{
		id: '2',
		name: 'Emma Kuusisto',
		prefix: null,
		phone: '08-489-046',
		picture: 'https://randomuser.me/api/portraits/med/women/67.jpg',
	},
	{
		id: '3',
		name: 'Siddharth Bangera',
		prefix: null,
		phone: '8462139119',
		picture: 'https://randomuser.me/api/portraits/med/men/37.jpg',
	},
	{
		id: '4',
		name: 'Olesya Kapustyanskiy',
		prefix: '(066)',
		phone: 'C90-6270',
		picture: 'https://randomuser.me/api/portraits/med/women/59.jpg',
	},
	{
		id: '5',
		name: 'Ruby Li',
		prefix: '(350)',
		phone: '806-8254',
		picture: 'https://randomuser.me/api/portraits/med/women/76.jpg',
	},
	{
		id: '6',
		name: 'Ingo Cardoso',
		prefix: '(64)',
		phone: '6321-4208',
		picture: 'https://randomuser.me/api/portraits/med/men/26.jpg',
	},
	{
		id: '7',
		name: 'Ria da Conceição',
		prefix: '(15)',
		phone: '7772-6293',
		picture: 'https://randomuser.me/api/portraits/med/women/90.jpg',
	},
	{
		id: '8',
		name: 'Paola Melo',
		prefix: '(42)',
		phone: '9146-3180',
		picture: 'https://randomuser.me/api/portraits/med/women/23.jpg',
	},
	{
		id: '9',
		name: 'Kathy Watts',
		prefix: '031',
		phone: '363-8332',
		picture: 'https://randomuser.me/api/portraits/med/women/27.jpg',
	},
	{
		id: '10',
		name: 'علی نجاتی',
		prefix: '066',
		phone: '76025733',
		picture: 'https://randomuser.me/api/portraits/med/men/3.jpg',
	},
];